apiVersion: v1
kind: Template
labels:
  template: graph-refresh-job-buildconfig
  thoth: 0.1.0
metadata:
  name: graph-refresh-job-buildconfig
  annotations:
    description: This is Thoth Core - Graph Refresh Job BuildConfig
    openshift.io/display-name: "Thoth: Graph Refresh Job BuildConfig"
    version: 0.2.0
    tags: poc,thoth,ai-stacks,graph,jansugraph
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Graph Refresh Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: graph-refresh-job
    labels:
      app: thoth-core
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "graph-refresh-job:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: ${GITHUB_URL}
        ref: ${GITHUB_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}

parameters:
- description: Name of the GitHub repository for Thoth's Graph Refresh Job
  displayName: Git Repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/graph-refresh-job'

- description: Git reference to be used for Thoth's Package Releases Job
  displayName: Git Reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'
